import numpy as np
import logging

#P_DEL = 0.02
P_DEL = 0.02
#P_SUB = 0.022
P_SUB = 0.022
#P_INS = 0.017
P_INS = 0.017
P_COR = 1 - P_DEL - P_SUB - P_INS

Alphabet = "ATGC"

TRACE_NUM = 4
#ORIGINAL = "T"*10
ORIGINAL = "".join(np.random.choice(list(Alphabet), size=100, replace=True))

CUSTOM_TRACES = ["ACCATAATGCGTGGGGCTGACCTCGGAATGCGTGGTCTCCATGCGCGTTTCCTCCAACCTAAGGTAGCCTGTAGTTCATTGACCTCTGATGGCGCTTATAGAAACCGGGAA",
                 "ACCATAATGCGTGGGGCCGACCTCGGAATGCGGTCTCCATGCGCGTTTCCTCAACCTAAGGTAGCCTGATTCATTGGACCTCTGATGGCGCTTATAGAAACTGGGGAA",
                 "ACCATAATGCGTGGGGCCGACCTCGGGAATGCGGTCTCCATGCGCGTTTCCTCCAACCTAAGGTAGCCTGTAGTTCATTGGACCTCTGATGGCGCTTATAGAAACCGGGAA",
                 "ACCATAATGCGTGGGCCGACCTCAGAATGCGGTCTCCATGCGCGTTTCCTCCAACCTAAGGTAGCCTGTAGTTCATTGGACCTCTGATGGCGCTTATAGAAACCGGGAA",
                 "ACCATAATGCGTGGGGCCGACCTCGGAGATGCGGTCACCATGCGCGTTTCCTCCAACCTAAGGTAGCCTGTAGTTCATTGGACCTCTGATGGCGCTTACTTATAGAAACCGGGA",
                 "ACCATAATGCGTGGGGCCGACTCCGGAATGCGGTCTCCATGCGCGTTTCTCCAACCTAAGGTAGCCTGTAGTTCATTGACCTCTGATGGCGCTTATGAAACCGGGAA",
                 "ACCATAATGCGTGGGGCCGACCTTCGGAATGCGGTCTCCATGCGCGTTTCCTCCAACCTAAGGTAGCCTGTAGTTCATTGGACCTCTGATGGCGCTTTATAGAAACCGGGAA",
                 "ACCATAATGCGTGGGGCCGACCTCCGGAATGCGGTCTCCATACGCGTTTTCCTCCAACCTAAGGTAGCCTGTAGTTCGTGGACCTCTGATGGCGCTTATAGAAACCGGGAGA",
                 "ACCATAATGCGTGGGGCCAGCCTCGGAATGCGGTCTCCATGCGCGTTCCTCCAACCTAAGGTAGCCACAGTTCATTTGGACCTCTGATGGCCTTATAGAAACCGGGAA",
                 "ACCATAATGCGTGGGGCCGACCTCGGAAATGCGGTCTCCATGCGCGTTTCCTCCAACCTAAGGTAGCCTTAGGAAGTTCATTGGACTCTGATGGCGCTTATAGAAACCGGGAA",
                 "ACCATAATGCGTGGGGCCGACCTCGGAATGCGGTCTCCATGCGCGTTTCCTCCAACCTAAGGGTAGCCTGCAGTTCATTGGACCTCTGATGGCGCTTATGGAAACCAGGA",
                 "ACCATAATGCGTGGGCAACCTCGGAATGCGGTCTCCATGCGCGTTTCCTCCAACCTAAGGTAGCCTGTAGTTCATTGGACCTCTGATGGCGCTTATAGGAAACCGGGAA",
                 "ACCATAATGCGTGGGGCCGACCTCGGAATGCGGTCTCCATGCGCGTTTCCCTCCAACCTAAAGGTAGCCTGCAGATTTCGTGGACCTCTGATGGCGCTTATAGAAACCGGGAA",
                 "ACCATAATGCGTGGGGCCGACCTCGGAATGCGGTCTCCATATACGTTTCTCCAACCTAAGGTAGCCTGTAGTTCATTGGACCTCTGATGGCGCTATAGAAACCGGGAA",
                 "ACCATAATGCGTGGGGCCGACCTCGGAATGCGGTCTCCATGCGCGTTTCCTCCAACCTAAGGTAGCCTGTAGTTCATTGGACCTCTGATGGCGCTTTTATAGAAACCGGGAA"
                 ]
CUSTOM_ORIGINAL = "ACCATAATGCGTGGGGCCGACCTCGGAATGCGGTCTCCATGCGCGTTTCCTCCAACCTAAGGTAGCCTGTAGTTCATTGGACCTCTGATGGCGCTTATAGAAACCGGGAA"

USE_NANOPORE_DATA_FROM_FILE = True
USE_CUSTOM_TRACES = True
USE_LOG_PROB = True

# optimization related
REMOVE_UNNEEDED_TRELLIS_SOURCES = False
LOGGING_LEVEL = logging.INFO
